<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>proophessor-do</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/assets/css/style.css">
<!--         <link rel="icon" href="http://static.gamers.dev/favicon.ico" /> -->
    </head>
    <body>
    	<header>
      		<?= $this->mainMenu(); ?>
		</header>

        <article class="col-sm-7 col-md-8">
            <?= $this->content; ?>
        </article>
        <hr>
        <footer>
            <p>&copy; 2017 by Coffee Game. All rights reserved.</p>
        </footer>
    </body>
</html>
