<ul>
    <?php foreach ($this->paths as $group => $pages):
    if ($group != 'heroes') continue; ?>
        <li class="page-group">
        	<?= $group ?>
            <ul>
            	<?php foreach ($pages as $name => $page): ?>
            	    <li>
            	    	<a href="<?= $this->serverUrl($this->url('heroPage', ['page' => $page['name']])) ?>">
            	    		<?= $name. ' - '?>
            	    	</a>
            	    </li>
            	<?php endforeach; ?>
            </ul>
        
    <?php endforeach; ?>
</ul>
