<nav id="top-menu"> 
    <ul>
        <?php foreach ($this->paths as $group => $pages): ?>
            <li class="page-group">
            	<?= $group ?>
                <ul>
                	<?php foreach ($pages as $name => $page): ?>
                	    <li>
                	    	<a href="<?= $this->serverUrl($this->url($this->routesMapping[$group], ['page' => $page['name']])).'.html' ?>">
                	    		<?= $name ?>
                	    	</a>
                	    </li>
                	<?php endforeach; ?>
                </ul>
            
        <?php endforeach; ?>
    </ul>
</nav>
    